### ISSUE TITLE
WARC with query parameter not found in CDXJ

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#595] opened 2018-11-01 19:47 UTC
I am using a WARC (attached) and unable to access the mementos within when using ipwb 0.2018.10.15.1346 from source via Docker. Performing the typical indexing procedure shows two captures (pictured). Clicking on a link results in a 404 for the URI-R `biorisk.pensoft.net/articles.php?id=1904` at `20181101192316`.

Strangely, the 404 reports:
`No capture found for biorisk.pensoft.net/articles.php?id=1904?id=1904`
^...note the extra query parameter.

Additionally, the CDXJ and Link TimeMap links on the 404 point to:
`http://localhost:5002/memento/20181101192316/biorisk.pensoft.net/timemap/link/ and `http://localhost:5002/memento/20181101192316/biorisk.pensoft.net/timemap/cdxj/`, which seems to indicate that the URI-R is being parsed incorrectly.

This is a compound issue.

Generated CDXJ:
```
!context ["http://tools.ietf.org/html/rfc7089"]
!meta {"created_at": "2018-11-01T19:30:29.255640", "generator": "InterPlanetary Wayback v.0.2018.10.15.1346"}
net,pensoft,biorisk)/article_preview.php?id=1904 20181101192316 {"locator": "urn:ipfs/QmcF6xX5XUrj19R9eZDTPLc27b4BNz8JH6mu76FUXu5AvP/QmacNjx3oyoy3q9gwwQCj6dv8AH3ybSMe8DVTmKZXmQoK5", "original_uri": "http://biorisk.pensoft.net/article_preview.php?id=1904", "title": "China in the anthropocene: Culprit, victim or last best hope for a global ecological civilisation?", "mime_type": "text/html;charset=utf-8", "status_code": "200"}
net,pensoft,biorisk)/articles.php?id=1904 20181101192316 {"locator": "urn:ipfs/QmVDfudfARdRxKu1pWmhsWrTLM4F4Lfwdw6qJx9K5aaTuA/QmdPDpQD2bLbQvHeJtEUxvyBvav4Tp1GMGMkyMtMU8Ye7w", "original_uri": "http://biorisk.pensoft.net/articles.php?id=1904", "title": "China in the anthropocene: Culprit, victim or last best hope for a global ecological civilisation?", "mime_type": "text/html;charset=utf-8", "status_code": "200"}
net,pensoft,biorisk)/i/aof_biorisk_logo.svg 20181101192316 {"locator": "urn:ipfs/QmWZQxXtu1LrF3ZCGZooLF7zaCVMQNBQ2bK863Yvgwmfgt/QmNt7Z5mG4J1SpfPLxAaZ3W374iHeYf72R2yQCr3C8tbRa", "original_uri": "http://biorisk.pensoft.net/i/AOF_biorisk_logo.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/i/author_icon.svg 20181101192316 {"locator": "urn:ipfs/QmRivgXtyen6HvLSN4iPJRXijbwtmjnqktLLa5jqEkLFro/QmT6PCvogu9HXwFcdGaGFkfsH1SsXryxetD6TYfoCRy7Dt", "original_uri": "http://biorisk.pensoft.net/i/author_icon.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/i/br-logo.svg 20181101192316 {"locator": "urn:ipfs/QmWyQinR4ibsuz3HgnHpTxv7kvSMEoJP6wi8Dje1x8rMqM/QmRpJiLXG3p6ZxL5Swga8vQVBcE3vGXnghCxmzRd5hhV1e", "original_uri": "http://biorisk.pensoft.net/i/BR-logo.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/i/cart-new.png 20181101192317 {"locator": "urn:ipfs/QmXSM75yerwm3fgX6AvLRpFCp5vvXeM1XBQmMVkxLcuynx/QmYN45gbdBMUEeUXGTkRKUEH2snudwtkaSBmYcjFb3HZpt", "original_uri": "http://biorisk.pensoft.net/i/cart-new.png", "mime_type": "image/png", "status_code": "200"}
net,pensoft,biorisk)/i/email_icon.svg 20181101192317 {"locator": "urn:ipfs/Qma3B6LWeqCqckLTXKspHM3TGh7fmJEddVoLKuQsNu8yW2/QmeidRfoeuqRFwPwRP5Tj382RDA7uqxhyYGmH12h7uTthg", "original_uri": "http://biorisk.pensoft.net/i/email_icon.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/i/open_access.svg 20181101192316 {"locator": "urn:ipfs/QmWGT3zUKz7ujo4cipoXtWveABeez5hQisjjQ4GVdSpaKJ/QmQGMicM2i4AmcDfTBuPewG67wktjHVzYeaWqKZ2LpdKGj", "original_uri": "http://biorisk.pensoft.net/i/open_access.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/i/pensoft_logo.svg 20181101192316 {"locator": "urn:ipfs/QmVekGPJTh2gajxCUfUv3K5kmUutyKJSzgY76iX4uGzmRP/QmURcyphAvaWbXzJRwFVED88ZYfTZiXoyomM5VnkLxUn6C", "original_uri": "http://biorisk.pensoft.net/i/pensoft_logo.svg", "mime_type": "image/svg+xml", "status_code": "200"}
net,pensoft,biorisk)/lib/ajax_srv/article_elements_srv.php?action=download_pdf&item_id=1904 20181101192316 {"locator": "urn:ipfs/QmQME5C46Qi6cCmutrHMhzjNHFpHQHQ7jMBcPmNDx2FiR2/QmNezVEESNezCVw926mgfAPgWvCQhAjrZpD29q5VUdfim6", "original_uri": "http://biorisk.pensoft.net/lib/ajax_srv/article_elements_srv.php?action=download_pdf&item_id=1904", "mime_type": "application/pdf", "status_code": "200"}
net,pensoft,biorisk)/lib/ajax_srv/generate_pdf.php?document_id=1904&readonly_preview=1 20181101192317 {"locator": "urn:ipfs/Qmez2cJ8y4MSzSWMpzJHnuEa5LbdZ8sdbsm9wxwPga4iv6/QmNezVEESNezCVw926mgfAPgWvCQhAjrZpD29q5VUdfim6", "original_uri": "http://biorisk.pensoft.net/lib/ajax_srv/generate_pdf.php?document_id=1904&readonly_preview=1", "mime_type": "application/pdf", "status_code": "200"}
```

![screen shot 2018-11-01 at 3 41 42 pm](https://user-images.githubusercontent.com/2514780/47875337-abd9d400-ddec-11e8-985e-cbcbe4f0aee2.png)

[tmpvgc6bkbf.warc.gz](https://github.com/oduwsdl/ipwb/files/2539827/tmpvgc6bkbf.warc.gz)

**Comment by machawk1** [comment] 2018-11-06 01:31
Using the above WARC, the call to `getCompleteURI()` in `show_uri()` is converting the passed in path value of `biorisk.pensoft.net/articles.php?id=1904` to `biorisk.pensoft.net/articles.php?id=1904?id=1904` (note duplicate query string), which is likely the cause of subsequent issues.

**Comment by machawk1** [comment] 2018-11-06 01:33
Perhaps the "Flask issue of clipping queryString" per the comment on `getCompleteURI()` is no more. More testing to come.

**Comment by machawk1** [comment] 2018-11-06 01:37
```python
qs = request.query_string.decode('utf-8')
if qs != '':
    uri += '?' + qs
```
...seems like the opposite logic that the function seeks to remedy. I think it ought to check for equality with the empty string and if so, append the `?` and decoded `qs` to the URI as retrieved from the `Request` instance.

**Comment by machawk1** [comment] 2018-11-06 01:42
Doing the above causes the `?` to not be appended at all in some instances due to the `request` context. A `qs != '' and '?' not in uri:` condition might instead assure that it is appended when needed and not unnecessarily.

**Comment by ibnesayeed** [comment] 2018-11-06 01:47
I think the problem is happening because `getCompleteURI` is getting called twice in some situations. For example, `showMemento` calls `resolveMemento` which internally calls `getCompleteURI`, then the `showMemento` calls `show_uri` in an `else` clause which again calls `getCompleteURI`. This causes double query parameter inclusion in the described scenario (there might be more).

**Comment by ibnesayeed** [comment] 2018-11-06 01:49
> Doing the above causes the `?` to not be appended at all in some instances due to the `request` context. A `qs != '' and '?' not in uri:` condition might instead assure that it is appended when needed and not unnecessarily.

I would suggest not to use such hacky techniques to further obfuscate and cover some buggy code flows.

**Comment by machawk1** [comment] 2018-11-06 01:49
Yes, likely, and the conditional check is using the same basis for appending, which does not change. I have added the above sanity check to prevent this. PR incoming.

**Comment by machawk1** [comment] 2018-11-06 01:52
>  I would suggest not to use such hacky techniques to further obfuscate and cover some buggy code flows.

I welcome a PR that does not resort to this but until then, we have a fix for the issue. If you want to work on a better fix, let me know and I will continue to write some tests to validate this change.

**Comment by ibnesayeed** [comment] 2018-11-06 01:53
I would suggest to use an `@app.before_request` decorator to make this change once in the beginning and create a separate property in the `request` object that holds potential URI-R, when applicable. This way, all the calls to get complete URI-R in different places will go away and the info will be available in a clean way.

**Comment by machawk1** [comment] 2018-11-06 01:57
@ibnesayeed Please implement that if you feel it is the best approach.

**Comment by ibnesayeed** [comment] 2018-11-06 02:09
This might have been fixed by simply changing `uri` parameter to original `urir` in `resp = show_uri(uri, newDatetime)` (and any other places where we might be supplying a modified URI for yet another round).

**Comment by machawk1** [comment] 2018-11-06 02:13
@ibnesayeed Mind that this is accounting a Flask bug where the query string parameters are not included in the URI per the inline comment.

**Comment by ibnesayeed** [comment] 2018-11-06 02:19
> Mind that this is accounting a Flask bug where the query string parameters are not included in the URI per the inline comment.

It is not a bug in Flask. As a standard practice in Flask and many alike frameworks routes are defined on request path, not the query parameters. The Latter is present in a separate attribute.

**Closed** 2020-04-23 14:36 UTC
Labels: bug, pending
