### ISSUE TITLE
Add option to specify an output file for cdxj

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#354] opened 2017-12-24 03:27 UTC
The current approach to generate the index file is to use it something like this:

```
$ ipwb index sample.warc > sample.cdxj
```

This works well, but there are situations where access to the `stdout` or redirecting it to a file is not easy. Also, when the indexer is being run along with some other things, the combined output on the `stdout` may generate an invalid index. This has been the case when I tried using it with Docker for example. Here is what I am looking for now, while keeping the default output on `stdout`, if `-o` or `--output` argument is passed with a filename (with any path), that file should be used for writing the index instead. Something like this:

```
$ ipwb index -o sample.cdxj sample.warc
```

**Comment by machawk1** [comment] 2017-12-24 16:05
Duplicate of #23. Closing this ticket in favor of the older one.

**Closed by machawk1** 2017-12-24 16:05 UTC
