### ISSUE TITLE
Perform dechunking at indexing time

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#592] opened 2018-10-18 21:35 UTC
Currently we are dechunking responses at replay time which means we perform the same task repeatedly as many times as a resource is requested and also losing the potential deduplication benefits. We should move this functionality in the indexer before pushing the content to the IPFS.

**Comment by machawk1** [comment] 2018-10-19 17:30
Also, this is a duplicate of #126. Closing.

**Closed by machawk1** 2018-10-19 17:30 UTC
Labels: enhancement, ipwb indexer, ipwb replay

**Comment by ibnesayeed** [comment] 2018-10-19 19:09
> ... and reuse the same method from both the indexer and replay.

Unless we want to play nice with already indexed (and pushed to the IPFS) records, we do not need to reuse it from the replay.
